[2024-06-25T22:13:03.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T22:13:03.808+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:13:03.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:13:03.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T22:13:03.824+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_movies> on 2024-06-25 00:00:00+00:00
[2024-06-25T22:13:03.835+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=765) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T22:13:03.836+0000] {standard_task_runner.py:63} INFO - Started process 766 to run task
[2024-06-25T22:13:03.836+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v1', 'get_movies', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpff4t3etv']
[2024-06-25T22:13:03.840+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask get_movies
[2024-06-25T22:13:03.876+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-25T22:13:03.933+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v1' AIRFLOW_CTX_TASK_ID='get_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-25T22:13:03.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T22:13:14.238+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T22:13:14.239+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/get_movies.py", line 16, in get_movies
    with open("data/movie_data.json", "w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/movie_data.json'
[2024-06-25T22:13:14.247+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_movie_dataset_v1, task_id=get_movies, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240625T221303, end_date=20240625T221314
[2024-06-25T22:13:14.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task get_movies ([Errno 2] No such file or directory: 'data/movie_data.json'; 766)
[2024-06-25T22:13:14.263+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T22:13:14.273+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T22:13:14.275+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-25T22:15:45.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T22:15:45.244+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:15:45.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [queued]>
[2024-06-25T22:15:45.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T22:15:45.258+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_movies> on 2024-06-25 00:00:00+00:00
[2024-06-25T22:15:45.262+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=863) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T22:15:45.263+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v1', 'get_movies', 'scheduled__2024-06-25T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmprb6n50zp']
[2024-06-25T22:15:45.264+0000] {standard_task_runner.py:63} INFO - Started process 864 to run task
[2024-06-25T22:15:45.264+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask get_movies
[2024-06-25T22:15:45.297+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v1.get_movies scheduled__2024-06-25T00:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-25T22:15:45.355+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v1' AIRFLOW_CTX_TASK_ID='get_movies' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T00:00:00+00:00'
[2024-06-25T22:15:45.357+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T22:16:35.820+0000] {logging_mixin.py:188} INFO - Ошибка при получении данных: 504
[2024-06-25T22:16:35.821+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T22:16:35.822+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T22:16:35.830+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=create_movie_dataset_v1, task_id=get_movies, run_id=scheduled__2024-06-25T00:00:00+00:00, execution_date=20240625T000000, start_date=20240625T221545, end_date=20240625T221635
[2024-06-25T22:16:35.866+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T22:16:35.877+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T22:16:35.879+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
