[2024-06-26T04:59:43.930+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T04:59:43.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_movie_dataset_v31.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [queued]>
[2024-06-26T04:59:43.952+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_movie_dataset_v31.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [queued]>
[2024-06-26T04:59:43.953+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-26T04:59:43.963+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): insert_data_to_db> on 2024-06-25 12:00:00+00:00
[2024-06-26T04:59:43.968+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5707) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T04:59:43.968+0000] {standard_task_runner.py:63} INFO - Started process 5709 to run task
[2024-06-26T04:59:43.969+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_movie_dataset_v31', 'insert_data_to_db', 'scheduled__2024-06-25T12:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpohq0hu6i']
[2024-06-26T04:59:43.970+0000] {standard_task_runner.py:91} INFO - Job 166: Subtask insert_data_to_db
[2024-06-26T04:59:44.004+0000] {task_command.py:426} INFO - Running <TaskInstance: create_movie_dataset_v31.insert_data_to_db scheduled__2024-06-25T12:00:00+00:00 [running]> on host ad6ccfebc5a6
[2024-06-26T04:59:44.058+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_movie_dataset_v31' AIRFLOW_CTX_TASK_ID='insert_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T12:00:00+00:00'
[2024-06-26T04:59:44.059+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T04:59:44.066+0000] {sql.py:276} INFO - Executing: 
[2024-06-26T04:59:44.072+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-06-26T04:59:44.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T04:59:44.073+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 409, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2024-06-26T04:59:44.079+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_movie_dataset_v31, task_id=insert_data_to_db, run_id=scheduled__2024-06-25T12:00:00+00:00, execution_date=20240625T120000, start_date=20240626T045943, end_date=20240626T045944
[2024-06-26T04:59:44.087+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 166 for task insert_data_to_db (List of SQL statements is empty; 5709)
[2024-06-26T04:59:44.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T04:59:44.111+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T04:59:44.114+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
