[2024-07-01T00:34:46.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-01T00:34:46.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v8.train_model scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-01T00:34:46.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v8.train_model scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-01T00:34:46.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-01T00:34:46.716+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-06-30 00:00:00+00:00
[2024-07-01T00:34:46.722+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=873) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-01T00:34:46.723+0000] {standard_task_runner.py:63} INFO - Started process 894 to run task
[2024-07-01T00:34:46.723+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v8', 'train_model', 'scheduled__2024-06-30T00:00:00+00:00', '--job-id', '687', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmpaqlhimb3']
[2024-07-01T00:34:46.724+0000] {standard_task_runner.py:91} INFO - Job 687: Subtask train_model
[2024-07-01T00:34:46.759+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v8.train_model scheduled__2024-06-30T00:00:00+00:00 [running]> on host 52eea2daf696
[2024-07-01T00:34:46.835+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v8' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T00:00:00+00:00'
[2024-07-01T00:34:46.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-01T00:34:46.845+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-01T00:34:46.845+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/model_training.py", line 55, in main
    x = pd.read_json(
        ^^^^^^^^^^^^^
TypeError: read_json() takes 1 positional argument but 2 were given
[2024-07-01T00:34:46.853+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=model_training_v8, task_id=train_model, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20240701T003446, end_date=20240701T003446
[2024-07-01T00:34:46.861+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 687 for task train_model (read_json() takes 1 positional argument but 2 were given; 894)
[2024-07-01T00:34:46.897+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-01T00:34:46.909+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-01T00:34:46.912+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
